config/routes.rb
Rails.application.routes.draw do
  
  # get 'errors/not_found'
  namespace :seller do
    resources :subscriptions do
      member do
        get :portalsession
      end
    end
    resources :product
    resources :shop
  end

  namespace :admin do
    resources :category
    resources :plan
    resources :subcategory do
      member do
        get :check_promo
        get :promocode
      end
    end
    resources :order
    resources :promo do
      member do
        get :check_promo
      end
    end
  end

  resources :category, :only => [:show] do
    member do
      get :get_products
    end
  end
  
    resources :product, :only => [:show] do
      member do
        get :search
      end
    end
    resources :subcategory, :only => [:show]
    resources :home , :only => [:index]
    resources :order do
      member do
        get :authentication
      end
    end
    resources :review
    resources :authentication
    resources :webhook, only: [:create]

  devise_for :users, :controllers => {:registrations => "users/registrations", :sessions => "users/sessions", omniauth_callbacks: 'users/omniauth_callbacks'}
  
  get 'shoppingcart/:id' => "shoppingcart#show", as: "cart"
  delete 'shoppingcart/:id' => "shoppingcart#destroy"

  root 'home#index' 
  get 'cart_item/:id/add' => "cart_item#add_quantity", as: "cart_item_add"
  get 'cart_item/:id/reduce' => "cart_item#reduce_quantity", as: "cart_item_reduce"
  post 'cart_item' => "cart_item#create"
  get 'cart_item/:id' => "cart_item#show"
  delete 'cart_item/:id' => "cart_item#destroy"
  post 'seller/promo/add_product' => "seller/promo#add_product"

  put '/review/:id/like', to: 'review#like', as: 'like'
  get 'shoppingcart' => "shoppingcart#show"


  # match '*path', :to => redirect('/404_Not_Found.html'), via: :all
  
  
end

app/models/product.rb
class Product < ApplicationRecord
    include DiscountExtension

    before_create :check_seller_plan

    mount_uploaders :images, ImageUploader  

    has_many :product_categories, dependent: :destroy
    has_many :sub_categories, through: :product_categories
    has_one :category
    
    has_many :cart_items, dependent: :destroy
    has_many :order_items, dependent: :destroy

    has_many :reviews, dependent: :destroy
    has_rich_text :description

    belongs_to :promo, optional: true
    belongs_to :shop, optional: true

    has_many :likes

    scope :searched, -> (name) { joins(:sub_categories).where("lower(sub_categories.title) LIKE ? OR lower(name) LIKE ? OR lower(description) LIKE ?", name.downcase, name.downcase, name.downcase) }
    
    scope :product_by_category, -> (id) {joins(:sub_categories).where(:sub_categories => {:category_id => id})}

    scope :recommended_products, -> (recommended_categories) {joins(:sub_categories).where.not(sub_categories: {:id => recommended_categories})}

    def liked?(user)
        !!self.likes.find{|like| like.user_id == user.id}
    end

    def self.reduce_stock(cart_item, product)
        if cart_item.quantity == 1
            cart_item.destroy
            product.stock +=1
        else
            cart_item.quantity -= 1
            product.stock+=1
        end
    end

    def check_seller_plan   
        product_count = self.shop.products.where('created_at > ?', DateTime.now.beginning_of_month).count
        plan = self.shop.user.plan
        case plan.name
        when 'Premium Plan'
            if product_count >= plan.no_of_products || self.images.length > plan.no_of_images
                self.errors.add(:created_at, 'You have reached your limit for this month')
                throw :abort
            else
                return true
            end
        when 'Gold Plan'
            if product_count >= plan.no_of_products || self.images.length > plan.no_of_images
                self.errors.add(:created_at, 'You have reached your limit for this month')
                throw :abort
            else
                return true 
            end
        when 'Basic Plan'
            if product_count >= plan.no_of_products || self.images.length > plan.no_of_images
                self.errors.add(:created_at, 'You have reached your limit for this month')
                throw :abort
            else
                return true
            end
        end
    end

    
end

app/controllers/product_controller.rb
class ProductController < ApplicationController

    def show
        @product = Product.find(params[:id])
        @reviews = @product.reviews
    end

    def search
        name = "%#{params[:product][:name]}%"
        @products = Product.searched(name)
    end
end

app/controllers/seller/product_controller.rb
class Seller::ProductController < ApplicationController

  load_and_authorize_resource
  
    def index
      @shop = current_user.shop
      @products = @shop.products.all
    end
    def new
      @categories = Category.all
      @subcategories = SubCategory.all
    end
  
    def create
        @shop = current_user.shop
        @product = @shop.products.new(product_params)
        if @product.save
          @product_category = ProductCategory.new(product_id: @product.id ,:sub_category_id=> params[:product][:sub_categories])
          @product_category.save
          redirect_to new_seller_product_path
          flash.notice = "Product Added Successfully!"
        else 
          redirect_to new_seller_product_path
          flash.alert = "Product Added Successfully!"
        end
    end

    def edit
      @product = Product.find(params[:id])
      @categories = Category.all
      @subcategories = SubCategory.all
    end

    def update
      @product = Product.update(product_params)
    end
  
    private
    
    def product_params
      params.require(:product).permit(:name, :description, {images:[]}, :price, :quantity, :stock)
    end
  end
  

app/helpers/product_helper.rb
module ProductHelper
end

app/views/admin/product/index.html.erb
<div class="container">
<div class="table-responsive"  style="padding-left:170px">
  <!--Table-->
  <table class="table table-striped" >

    <!--Table head-->
    <thead>
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>Categories</th>
        <th>Price</th>
        <th>Action</th>
      </tr>
    </thead>
    <!--Table head-->

    <!--Table body-->
    <tbody>
    <%x=1%>
    
    <% @products.each do |product| %>
   
    <tr>
    <td><%= x %></td>
    <td><%= product.name %></td>
    <% product.sub_categories.each do |category| %>
    <td><%=category.title%></td>
    <%end%>
    <td><%= product.price %></td>
    <td><%= link_to 'Edit Product', "" , :class => 'btn btn-primary btn-block ', :style => 'margin:0 auto; color:white' %></td>
    </tr>
    <%x = x+1 %>
    <%end%>
    </tbody>
    <!--Table body-->
  </table>
  <!--Table-->
</div>
</div>
<div>

app/views/admin/product/new.html.erb
<div class="container py-5">
    <div class="row d-flex justify-content-center align-items-center" style="margin-left:170px;">
      <div class="col-12 col-md-12 col-lg-12 col-xl-12">
        <div class="card shadow-2-strong" style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">
            <h3 class="mb-5">Add Product</h3>
            <%= form_for :product , url: admin_product_index_path, class: 'form-group' do |f| %>
            <div class="form-outline mb-4" style='text-align:left'>
              Name : <%= f.text_field :name, class: 'form-control', class:'form-control form-control-lg'%><br />
            </div>  

            <div class="form-outline mb-4" style='text-align:left'>
              Categories : <br />
              <%= f.select(:category, options_from_collection_for_select(@categories.all, :id, :title), :id => 'category') %>
              <br /> SubCategories :<br />
               <%= f.select(:subcategory, '', :id => "subcategory_id") %>
            </div>
            <div class="form-outline mb-4" style='text-align:left'>
              Description : <%= f.rich_text_area :description%><br />
            </div>
            <div class="form-outline mb-4" style='text-align:left'>
              Price : <%= f.text_field :price, class: 'form-control', class:'form-control form-control-lg'%><br />
            </div>
            <div class="form-outline mb-4" style='text-align:left'>
              Stock Quantity : <%= f.number_field :stock, class: 'form-control', class:'form-control form-control-lg'%><br />
            </div>
            <div class="form-outline mb-4" style='text-align:left; margin-bottom:10px;'>
            Product Images :<%= f.file_field :images,multiple:true, class: "form-control-file", id:"exampleFormControlFile1", style: "margin:10px;" %><br />
            </div>
            <%= f.submit "Submit", class:"btn btn-primary btn-lg btn-block" %>
            
            <% end %>
        </div>
      </div>
    </div>
  </div>
  <script>
  $(document).ready(function(){
   $('select[name="product[category]"]').on('change',function(){
    
       var category_id = $(this).val();
       if (category_id) {
          $.ajax({
            url: `/admin/subcategory/${category_id}`,
            type:"GET",
            dataType:"script",
            succsess: function(data) {
              alert(data)
            },
          });

        }else{
          alert('danger');
        }

          });
    });
  </script>