config/routes.rb
Rails.application.routes.draw do
  
  # get 'errors/not_found'
  namespace :seller do
    resources :subscriptions do
      member do
        get :portalsession
      end
    end
    resources :product
    resources :shop
  end

  namespace :admin do
    resources :category
    resources :plan
    resources :subcategory do
      member do
        get :check_promo
        get :promocode
      end
    end
    resources :order
    resources :promo do
      member do
        get :check_promo
      end
    end
  end

  resources :category, :only => [:show] do
    member do
      get :get_products
    end
  end
  
    resources :product, :only => [:show] do
      member do
        get :search
      end
    end
    resources :subcategory, :only => [:show]
    resources :home , :only => [:index]
    resources :order do
      member do
        get :authentication
      end
    end
    resources :review
    resources :authentication
    resources :webhook, only: [:create]

  devise_for :users, :controllers => {:registrations => "users/registrations", :sessions => "users/sessions", omniauth_callbacks: 'users/omniauth_callbacks'}
  
  get 'shoppingcart/:id' => "shoppingcart#show", as: "cart"
  delete 'shoppingcart/:id' => "shoppingcart#destroy"

  root 'home#index' 
  get 'cart_item/:id/add' => "cart_item#add_quantity", as: "cart_item_add"
  get 'cart_item/:id/reduce' => "cart_item#reduce_quantity", as: "cart_item_reduce"
  post 'cart_item' => "cart_item#create"
  get 'cart_item/:id' => "cart_item#show"
  delete 'cart_item/:id' => "cart_item#destroy"
  post 'seller/promo/add_product' => "seller/promo#add_product"

  put '/review/:id/like', to: 'review#like', as: 'like'
  get 'shoppingcart' => "shoppingcart#show"


  # match '*path', :to => redirect('/404_Not_Found.html'), via: :all
  
  
end

app/models/order.rb
class Order < ApplicationRecord
    enum status: {pending: 0, shipped: 1, delivered: 2 }

    belongs_to :user
    has_many :order_items, dependent: :destroy
    has_many :products, through: :order_items

    def self.set_status(order)
        case order.status
        when 'shipped'
          order.status = 'pending'
        when 'pending'
          order.status = 'shipped'
        end
    end

end

app/controllers/admin/order_controller.rb
class Admin::OrderController < ApplicationController  

  load_and_authorize_resource
    def index
        @orders = Order.all
      end
    
      def show
        @order = Order.find(params[:id])
        @order_items = @order.order_items
      end

      def update
        @order = Order.find(params[:id])
        Order.set_status(@order)
        @order.save
        redirect_to admin_order_path(@order.id)
        end

end

app/controllers/order_controller.rb
class OrderController < ApplicationController

      def index
        @orders = current_user.order.all
      end
    
      def show
        @order = current_user.order.find(params[:id])
        @order_items = @order.order_items
      end
      
      def new
        @order = Order.new
        @cart = current_user.shoppingcart.cart_items
        @otp = SecureRandom.hex(5)
      end   

      def authentication
        AuthenticationMailer.otp(params[:email], params[:otp]).deliver_now
      end
      
      def create
        cart_items = current_user.shoppingcart.cart_items  
        promo = params[:order][:promo]
        if promo != nil
        promo_items = cart_items.discounted_items(promo)
        end
        @order = current_user.order.new(order_params)
        current_cart = current_user.shoppingcart
        cart_items = current_cart.cart_items
        CartItem.createOrderItems(@order, current_cart, cart_items, promo_items)
        if @order.save
          current_cart.cart_items.delete_all
          flash.notice = "Your Order Has Been Successfully Placed!"
          redirect_to home_index_path
        else
          flash.alert = "Your Order Cannot be Placed at the moment, Please try later!"
          redirect_to home_index_path
        end
      end

      private
        def order_params
          params.require(:order).permit(:name, :email, :address, :pay_method,:lastname)
        end
        
end

app/helpers/order_helper.rb
module OrderHelper
end

app/views/order/index.html.erb
<div class="container" style="margin-top: 10px;">
<center style="margin-top:30px"><h4>Order History</h4></center>
<div class="table-responsive">
<div class="row">
  <% @orders.each do |order|%>
    
    <div class="col-lg-6">
    <div class="card mb-4" style="padding: 30px">
    <h6> Order id:  <%=order.id%> </h6>
        <table class="table table-borderless">
            <tbody>
            <%total = 0%>
            <%order.order_items.each do |item|%>
            
              <tr>
                <td>
                  <div class="d-flex mb-2">
                  
                    <div class="flex-shrink-0">
                    <%if item.product.images.present?%>
                        <%= image_tag  (item.product.images.last.url), style: 'width:35px' %>       
                    <%else%>
                        <img class="card-img-top" src="https://dummyimage.com/300x300/dee2e6/6c757d.jpg" alt="..." />
                    <%end%>
                    </div>
                    <div class="flex-lg-grow-1 ms-3">
                      <h6 class="small mb-0"><a href="#" class="text-reset"><%=item.product.name%></a></h6>
                    </div>
                  </div>
                </td>
                <td><%=item.quantity%></td>
                <td class="text-end"><%=item.price %> </span>
                    <%total = item.price + total%>
              </tr>
            <%end%>
            </tbody>
            <tfoot>
              <tr class="fw-bold">
                <td colspan="2">TOTAL</td>
                <td class="text-end">$ <%=total%></td>
              </tr>
              <tr>
              <td colspan="2">STATUS</td>
              <td class="text-end"><span class="add-to-cart btn btn-default" style="cursor:default;"><%=order.status%></span></td>
                </tr>
            </tfoot>
          </table>
          </div>
    </div>
  <% end %>
  </div>
  </div>

app/views/order/new.html.erb
<div class="container">
    <div class="py-5 text-center">
        <h2>Checkout form</h2>
    </div>
    <div class="row">
        <div class="col-md-4 order-md-2 mb-4">
            <h4 class="d-flex justify-content-between align-items-center mb-3">
                <span class="text-muted">Your cart</span>
                <%totals = 0%>
                <span class="badge badge-secondary badge-pill"><%@cart.each do|cart|%>
                <%totals = (cart.quantity).to_i + totals%>
                <%end%>
                Items: <%=totals%>
                </span>
            </h4>
           <div id="cart_totals">
           <%= render 'shared/cart_totals'%>
           </div>

            <div class="form-outline flex-fill">
            <h4 class="d-flex justify-content-between align-items-center mb-3">
                <span class="text-muted">Add PromoCode</span>
                </span>
            </h4>
            <%= form_for :subcategory, url: check_promo_admin_subcategory_path(current_user.shoppingcart.id), method: 'get', remote: true, class: 'form-group' do |f| %>
            <div class="form-outline mb-4" style='text-align:left'>
              Title : <%= f.text_field :name, class: 'form-control', class:'form-control form-control-lg'%><br />
            </div>

            <%= f.submit class:"btn btn-primary btn-lg btn-block" %>        

            <% end %>

            </div>
        </div>
        <div class="col-md-8 order-md-1" id="order_form">
           <%= render 'shared/order_form'%>
        </div>
    <script>
        function CreateOrder(auth){  
            otp = $('#otp_auth').val()
            if(auth == otp){
          $.ajax({
              url: `/order`,
              beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
              type: 'post',
              dataType: "html",
              data: $("form").serialize(),
              success: function(data){
                    $('#exampleModal').modal('hide'); 
                    $('.modal-backdrop').remove();
                    $("#success_tic").modal('show');
           }
          });
            }else{
                alert('please enter valid otp')
            }
      };
      function SendOtp(auth){  
            email = $('#email').val();
             if (email != ""){
            $.ajax({
              url: `/order/otp/authentication?otp=${auth}&email=${email}`,
              type: 'get',
              dataType: "script",
          });
      }else{

      }
      };

        

    </script>