config/routes.rb
Rails.application.routes.draw do
  
  # get 'errors/not_found'
  namespace :seller do
    resources :subscriptions do
      member do
        get :portalsession
      end
    end
    resources :product
    resources :shop
  end

  namespace :admin do
    resources :category
    resources :plan
    resources :subcategory do
      member do
        get :check_promo
        get :promocode
      end
    end
    resources :order
    resources :promo do
      member do
        get :check_promo
      end
    end
  end

  resources :category, :only => [:show] do
    member do
      get :get_products
    end
  end
  
    resources :product, :only => [:show] do
      member do
        get :search
      end
    end
    resources :subcategory, :only => [:show]
    resources :home , :only => [:index]
    resources :order do
      member do
        get :authentication
      end
    end
    resources :review
    resources :authentication
    resources :webhook, only: [:create]

  devise_for :users, :controllers => {:registrations => "users/registrations", :sessions => "users/sessions", omniauth_callbacks: 'users/omniauth_callbacks'}
  
  get 'shoppingcart/:id' => "shoppingcart#show", as: "cart"
  delete 'shoppingcart/:id' => "shoppingcart#destroy"

  root 'home#index' 
  get 'cart_item/:id/add' => "cart_item#add_quantity", as: "cart_item_add"
  get 'cart_item/:id/reduce' => "cart_item#reduce_quantity", as: "cart_item_reduce"
  post 'cart_item' => "cart_item#create"
  get 'cart_item/:id' => "cart_item#show"
  delete 'cart_item/:id' => "cart_item#destroy"
  post 'seller/promo/add_product' => "seller/promo#add_product"

  put '/review/:id/like', to: 'review#like', as: 'like'
  get 'shoppingcart' => "shoppingcart#show"


  # match '*path', :to => redirect('/404_Not_Found.html'), via: :all
  
  
end

app/views/shared/_added_to_cart.html.erb
<div id="success_tic" class="modal fade" role="dialog">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                <a class="close" href="#" data-dismiss="modal">&times;</a>
                <div class="page-body">
                <div class="head">
                <h4>Product has been added to cart</h4>
                </div>

            <h1 style="text-align:center;"><div class="checkmark-circle">
            <div class="background"></div>
            <div class="checkmark draw"></div>
            </div><h1>

            </div>
            </div>
                </div>

            </div>

app/views/shared/_admin_sidenav.html.erb
<style>
.sidebar {
  position: fixed;
  top: 0;
  bottom: 0;
  left: 0;
  padding: 58px 0 0; /* Height of navbar */
  box-shadow: 0 2px 5px 0 rgb(0 0 0 / 5%), 0 2px 10px 0 rgb(0 0 0 / 5%);
  width: 188px;
  z-index: 600;
}

@media (max-width: 991.98px) {
  .sidebar {
    width: 100%;
  }
}
.sidebar .active {
  border-radius: 5px;
  box-shadow: 0 2px 5px 0 rgb(0 0 0 / 16%), 0 2px 10px 0 rgb(0 0 0 / 12%);
}

.sidebar-sticky {
  position: relative;
  top: 0;
  height: calc(100vh - 48px);
  padding-top: 0.5rem;
  overflow-x: hidden;
  overflow-y: auto; /* Scrollable contents if viewport is shorter than content. */
}
</style>
<!--Main Navigation-->
<header>
  <!-- Sidebar -->
  <nav id="sidebarMenu" class="collapse d-lg-block sidebar collapse bg-white">
    <div class="position-sticky">
        <h4 style="margin-left:35px"><b>ADMIN PANEL</b></h4>
      <div class="list-group list-group-flush mx-3 mt-4">
        <p
          class="list-group-item list-group-item-action py-2 ripple dropdown-toggle">
        <i class="fas fa-tachometer-alt fa-fw me-3"></i><span>Categories</span>
        </p>
        <div class="dropdown-menu1" style= "margin-left:10px; margin-bottom:15px">
          <%= link_to 'View Categories', admin_category_index_path , :class => 'list-group-item list-group-item-action py-2 ripple' %>
          <%= link_to 'Add Categories', new_admin_category_path , :class => 'list-group-item list-group-item-action py-2 ripple' %>
        </div>
        <p
          class="list-group-item list-group-item-action py-2 ripple dropdown-toggle">
        <i class="fas fa-tachometer-alt fa-fw me-3"></i><span>Plans</span>
        </p>
        <div class="dropdown-menu1" style= "margin-left:10px; margin-bottom:15px">
          <%= link_to 'Add Plan', new_admin_plan_path , :class => 'list-group-item list-group-item-action py-2 ripple' %>
        </div>
        <p
          class="list-group-item list-group-item-action py-2 ripple dropdown-toggle">
        <i class="fas fa-tachometer-alt fa-fw me-3"></i><span>SubCategories</span>
        </p>
        <div class="dropdown-menu1" style= "margin-left:10px; margin-bottom:15px">
          <%= link_to 'View SubCategories', admin_subcategory_index_path , :class => 'list-group-item list-group-item-action py-2 ripple' %>
        </div>

        <a href="/admin/order" class="list-group-item list-group-item-action py-2 ripple">
          <i class="fas fa-chart-area fa-fw me-3"></i><span>Orders</span>
        </a>
         <p
          class="list-group-item list-group-item-action py-2 ripple dropdown-toggle">
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'list-group-item list-group-item-action py-2 ripple'  %>
        </p>
      </div>
    </div>
  </nav>
  <!-- Sidebar -->
  <!-- Navbar -->
</header>
<!--Main Navigation-->

<!--Main layout-->
<main style="margin-top: 58px;">
  <div class="container pt-4"></div>
</main>
<!--Main layout-->

app/views/shared/_cart_items.html.erb
 <% @cart.each do |cart| %>
        
        <div class="card rounded-3 mb-4">
          <div class="card-body p-4">
            <div class="row d-flex justify-content-between align-items-center">
              <div class="col-md-2 col-lg-2 col-xl-2">
                <%if cart.product.images.present?%>
                    <%= image_tag  (cart.product.images.first.url), style: 'width:100px' %>       
                <%else%>
                    <img class="card-img-top" src="https://dummyimage.com/300x300/dee2e6/6c757d.jpg" alt="..." />
                <%end%>
              </div>
              <div class="col-md-3 col-lg-3 col-xl-3">
                <p class="lead fw-normal mb-2"><%=cart.product.name%></p>
              </div>
              <div class="col-md-3 col-lg-3 col-xl-2 d-flex">
                   <button id='reduce<%=cart.id%>' onclick='reduceQuantity(<%=cart.id%>,<%=cart.product.stock%>)' class='btn btn-link px-2' <%= cart.quantity == 1 ? 'disabled' : ''%> >
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-dash-circle-fill" viewBox="0 0 16 16">
                <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM4.5 7.5a.5.5 0 0 0 0 1h7a.5.5 0 0 0 0-1h-7z"/>
                </svg></button>

                <h2 id='quantity<%=cart.id%>'><%=cart.quantity%></h2>

                    <button id='add<%=cart.id%>' onclick='addQuantity(<%=cart.id%>,<%=cart.product.stock%>)' class='btn btn-link px-2' <%=cart.product.stock <= 1 ? 'disabled' : ''%>>
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-circle-fill" viewBox="0 0 16 16">
                    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.5 4.5a.5.5 0 0 0-1 0v3h-3a.5.5 0 0 0 0 1h3v3a.5.5 0 0 0 1 0v-3h3a.5.5 0 0 0 0-1h-3v-3z"/>
                    </svg></button>
              </div>
              <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">

               <h5 class="mb-0" id = "price<%=cart.id%>"> $ 
                <%if !@promo_items.nil?%>

                    <%@promo_items.each do |discounted_item|%>

                          <%= cart.get_price(discounted_item)%>

                    <%end%> 
                    <%if cart.product.sub_categories.last.code.nil?%>
                    <%= cart.orignial_price%>
                    <%end%>

                <%else%>
                    <%= cart.orignial_price%>
                <%end%>
               
               </h5>

              </div>
              <div class="col-md-1 col-lg-1 col-xl-1 text-end">
              <a href='cart_item/<%=cart.id%>' method='delete'>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                </svg></a>

              </div>
            </div>
          </div>
        </div>


        <%end%>

app/views/shared/_cart_totals.html.erb
 <% @cart.each do |cart| %>
        <div class="card rounded-3 mb-1">
          <div class="card-body p-2">
            <div class="row">
              <div class="col-md-6 col-lg-6 col-xl-6">
                <h6 class="mb-0"><%=cart.product.name%></h6>
              </div>
              <div class="col-md-6 col-lg-6 col-xl-6">

               <h5 class="mb-0" id = "price<%=cart.id%>" style="tex-align:right"> $ 
                <%if !@promo_items.nil?%>

                    <%@promo_items.each do |discounted_item|%>
                        
                          <%= cart.get_price(discounted_item)%>

                    <%end%> 
                    <%if cart.product.sub_categories.last.code != @promo%>
                    <%= cart.orignial_price%>
                    <%end%>

                <%else%>
                    <%= cart.orignial_price%>
                <%end%>
               
               </h5>

              </div>
            </div>
          </div>
        </div>


        <%end%>

app/views/shared/_categories.html.erb
<div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                   <% @products.each do |product|%>
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <%if product.images.present?%>
                            <%= image_tag  (product.images.last.url) %>
                            
                            <%else%>
                            <img class="card-img-top" src="https://dummyimage.com/300x300/dee2e6/6c757d.jpg" alt="..." />
                            <%end%>
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder"><%=product.name%></h5>
                                    <p><b>Category: </b><%=product.sub_categories.last.category.title%></p>
                                    <p><b>SubCategory: </b><%=product.sub_categories.last.title%></p>
                                    <!-- Product price-->
                                    $ <%=product.price%>
                                </div>
                            </div>
                   
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent" style="text-align:center">
                                <%= link_to 'View', product_path(product.id), method: 'get', :class => 'btn btn-outline-dark mt-auto', :style => 'margin:10px auto' %><br />
                               <%if product.stock > 1%>
                                <button id='add_cart' onclick='addtocart(<%=product.id%>,<%=user_signed_in?%>)' class='btn btn-outline-dark mt-auto'> Add To Cart </button>
                                <%elsif product.stock <= 1%>
                                <button id='add_cart' class='btn btn-outline-dark mt-auto'> Out of stock </button>
                                <%end%>
                            </div>
                        </div>
                    </div>
                     <%end%>
                </div>
                

app/views/shared/_nav_bar.html.erb
<style>
a:hover {
  color: #fff;
  background-color: lightgray !important
}
</style>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="#!"><%= image_tag "logo.png", width:'100px' %></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <%= link_to 'Shop', home_index_path , :class => 'nav-link' %>
                        <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Categories
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <% Category.all.each do |category|%>
                        <%= link_to category.title, category_path(category.id) , :class => 'dropdown-item' %>
                        <%end%>
                        </div>
                         <%if current_user!= nil%>
                       <li> <%= link_to 'Orders', order_index_path , :class => 'nav-link' %></li><%end%>
                        <li>  <div class="input-group">
                            <%= form_for(:product , url: search_product_path('result'), method: :get) do |f| %>
                            <%= f.text_field :name, class: 'form-control', placeholder:"Search for product"%><br />
                            <div class="input-group-append">
                                <%= f.submit :search, class:"fa fa-search"%>
                            </div>
                            <%end%>
                        </div></li>
                    </li>
                    </ul>
                        <%if current_user!= nil%>
                         <a href="/shoppingcart" class="add-to-cart btn btn-default" type="submit">
                            <i class="bi-cart-fill me-1"></i>
                            Cart
                            <span class="badge bg-dark text-white ms-1 rounded-pill" id="cart_quantity"><%=current_user.shoppingcart.cart_items.all.count%></span>
                        </a>
                        
                        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'add-to-cart btn btn-default', style: "margin-left:10px"  %>   
                        <%else%>
                            <%= link_to "Log in", new_user_session_path, :class => 'add-to-cart btn btn-default', style: "margin-left:10px" %><br />

                            <%= link_to "Sign up", new_user_registration_path, :class => 'add-to-cart btn btn-default', style: "margin-left:10px" %><br />
                        <%end%>

                </div>
            </div>
        </nav>

app/views/shared/_order_form.html.erb
 
 <h4 class="mb-3">Billing address</h4>
            <%= form_for(:order, as: @order , url: order_index_path, id: 'form' ) do |f| %>
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <%= f.label :name, 'First Name' %><br>
                        <%= f.text_field :name, required: true, autofocus: true, class: "form-control"%>
                        <div class="invalid-feedback"> Valid first name is required. </div>
                    </div>
                    <div class="col-md-6 mb-3">
                        <%= f.label :lastname , 'Last Name'%><br>
                        <%= f.text_field :lastname, required: true, autofocus: true, class: "form-control"%>
                        <div class="invalid-feedback"> Valid last name is required. </div>
                    </div>
                </div>
                <div class="mb-3">
                    <%= f.label :email %><br>
                    <%= f.email_field :email, class:"form-control", id:"email"%>
                    <div class="invalid-feedback"> Please enter a valid email address for shipping updates. </div>
                </div>
                <%if !@promo.nil?%>
                <%= f.hidden_field :promo, value: @promo%>
                <%end%>
                <div class="mb-3">
                    <%= f.label :address %><br>
                    <%= f.text_area :address, class:"form-control" %>
                    <div class="invalid-feedback"> Please enter your shipping address. </div>
                </div>
                <hr class="mb-4">
                <h4 class="mb-3">Payment</h4>
                <div class="d-block my-3">
                    <div class="custom-control custom-radio">
                       <%= f.radio_button :pay_method, 'cod', :checked => true %> 
                      <%= label :contactmethod_cod, 'Cash On Delivery' %>
                      <%= f.radio_button :pay_method, 'debit' %>
                      <%= label :contactmethod_debit, 'Debit/Credit Card' %>
                    </div>
                </div>
                <hr class="mb-4">
                             <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Order Authentication</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body" id="enter_otp">
                        Please Enter Otp Sent To Your Entered Email!
                        <input type="text" id='otp_auth' class="form-control">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <div id="order_submit" class='btn btn-primary' style="width:200px; text-align:center; cursor:pointer" onclick="CreateOrder('<%=@otp%>')"> submit </div>
                    </div>
                    </div>
                </div>
                </div>
                
                <button type="button" class="btn btn-primary btn-lg btn-block" data-toggle="modal" data-target="#exampleModal" onclick="SendOtp('<%=@otp%>')">
            Confirm Order
            </button>
                
            </form>
                </div>
                
<% end %>
            <div id="success_tic" class="modal fade" role="dialog">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                <a class="close" href="#" data-dismiss="modal">&times;</a>
                <div class="page-body">
                <div class="head">  
                <%# <h3 style="margin-top:5px;">ORDER SUCCESSFULL!</h3> %>
                <h4>Your Order Has been successfully placed!</h4>
                </div>

            <h1 style="text-align:center;"><div class="checkmark-circle">
            <div class="background"></div>
            <div class="checkmark draw"></div>
            </div><h1>

            </div>
            </div>
                </div>

            </div>

app/views/shared/_product_card.html.erb
<div class="container-fluid bg-trasparent my-4 p-3" style="position: relative">
  <div class="row row-cols-1 row-cols-xs-2 row-cols-sm-2 row-cols-lg-4 g-3">
    <% @products.each do |product| %>
    <div class="col"> 
      <div class="card h-100 shadow-sm">
       <%if product.images.present?%>
            <%= image_tag  (product.images.last.url) %>                    
       <%else%>
            <img class="card-img-top" src="https://dummyimage.com/300x300/dee2e6/6c757d.jpg" alt="..." />
       <%end%>
        
        <div class="card-body">
          <div class="clearfix mb-3">
            <span class="float-start badge rounded-pill bg-success">
            <%if product.shop != nil && product.shop.discount?%>
                $ <del><%=product.price%></del> <ins><%=product.get_discount()%></ins> <br/>

            <%else%>
                $ <%=product.price%>
            <%end%>
            </span>
            <%# <span class="float-end"><a href="#" class="small text-muted text-uppercase aff-link">reviews</a></span> %>
          </div>
          <h5 class="card-title">
                <%=product.name%>
          </h5>

          <div class="d-grid gap-2 my-4">
                <%= link_to 'View', product_path(product.id), method: 'get', :class => 'add-to-cart btn btn-default', :style => '' %><br />
             <%if product.stock > 1%>
                <button id='add_cart' onclick='addtocart(<%=product.id%>,<%=user_signed_in?%>)' class='add-to-cart btn btn-default'> Add To Cart </button>
            <%elsif product.stock <= 1%>
                <button id='add_cart' class='btn btn-outline-dark mt-auto'> Out of stock </button>
            <%end%>
          </div>

        </div>
       
      </div>
       
    </div>
    <%end%>
</div>
</div>

app/views/shared/_seller_dash.html.erb
  <header id="header" class="header fixed-top d-flex align-items-center">
   <a class="navbar-brand" href="#!"><%= image_tag "logo.png", width:'100px' %></a>
  </header>

  
  <aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">
    <div id = 'notifications'></div>
        <li class="nav-heading">My Shop</li>
      
      <li class="nav-item">
      <%= link_to 'Plans', new_seller_subscription_path , :class => 'nav-link collapsed' %>
       <%= link_to 'Edit', edit_seller_shop_path(current_user.shop.id) , :class => 'nav-link collapsed' %>
        </a>
      </li>

      <li class="nav-heading">PRODUCTS</li>

      <li class="nav-item">
       <%= link_to 'View Products', seller_product_index_path , :class => 'nav-link collapsed' %>
        </a>
      </li>

      <li class="nav-item">
        <%= link_to 'New Product', new_seller_product_path , :class => 'nav-link collapsed' %>
        </a>
      </li>

      <li class="nav-item">
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'nav-link collapsed'  %>
        </a>
      </li>

    </ul>

  </aside>

app/views/shared/_show_ratings.html.erb
<%@reviews.each do |review|%>
            <p><strong>Description : </strong><%=raw(review.description)%></p>
            <p><strong>Rating : </strong>
            <div id="rateYo<%=review.id%>"></div> 
            </p>
            <p>Reviewed by: <%=review.user.name%> </p>

            <hr>
              <script>
                $("#rateYo"+ <%= review.id %> +"").rateYo({
                    rating: <%= review.rating %>,
                    readOnly: true
                });
                $ ('#rateYo'+ <%= review.id %> +"").attr('data-rateyo-read-only','true');
  
              </script>
        <%end%>