config/routes.rb
Rails.application.routes.draw do
  
  # get 'errors/not_found'
  namespace :seller do
    resources :subscriptions do
      member do
        get :portalsession
      end
    end
    resources :product
    resources :shop
  end

  namespace :admin do
    resources :category
    resources :plan
    resources :subcategory do
      member do
        get :check_promo
        get :promocode
      end
    end
    resources :order
    resources :promo do
      member do
        get :check_promo
      end
    end
  end

  resources :category, :only => [:show] do
    member do
      get :get_products
    end
  end
  
    resources :product, :only => [:show] do
      member do
        get :search
      end
    end
    resources :subcategory, :only => [:show]
    resources :home , :only => [:index]
    resources :order do
      member do
        get :authentication
      end
    end
    resources :review
    resources :authentication
    resources :webhook, only: [:create]

  devise_for :users, :controllers => {:registrations => "users/registrations", :sessions => "users/sessions", omniauth_callbacks: 'users/omniauth_callbacks'}
  
  get 'shoppingcart/:id' => "shoppingcart#show", as: "cart"
  delete 'shoppingcart/:id' => "shoppingcart#destroy"

  root 'home#index' 
  get 'cart_item/:id/add' => "cart_item#add_quantity", as: "cart_item_add"
  get 'cart_item/:id/reduce' => "cart_item#reduce_quantity", as: "cart_item_reduce"
  post 'cart_item' => "cart_item#create"
  get 'cart_item/:id' => "cart_item#show"
  delete 'cart_item/:id' => "cart_item#destroy"
  post 'seller/promo/add_product' => "seller/promo#add_product"

  put '/review/:id/like', to: 'review#like', as: 'like'
  get 'shoppingcart' => "shoppingcart#show"


  # match '*path', :to => redirect('/404_Not_Found.html'), via: :all
  
  
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :plan
end

app/controllers/seller/product_controller.rb
class Seller::ProductController < ApplicationController

  load_and_authorize_resource
  
    def index
      @shop = current_user.shop
      @products = @shop.products.all
    end
    def new
      @categories = Category.all
      @subcategories = SubCategory.all
    end
  
    def create
        @shop = current_user.shop
        @product = @shop.products.new(product_params)
        if @product.save
          @product_category = ProductCategory.new(product_id: @product.id ,:sub_category_id=> params[:product][:sub_categories])
          @product_category.save
          redirect_to new_seller_product_path
          flash.notice = "Product Added Successfully!"
        else 
          redirect_to new_seller_product_path
          flash.alert = "Product Added Successfully!"
        end
    end

    def edit
      @product = Product.find(params[:id])
      @categories = Category.all
      @subcategories = SubCategory.all
    end

    def update
      @product = Product.update(product_params)
    end
  
    private
    
    def product_params
      params.require(:product).permit(:name, :description, {images:[]}, :price, :quantity, :stock)
    end
  end
  

app/controllers/seller/shop_controller.rb
class Seller::ShopController < ApplicationController
    load_and_authorize_resource
    
    def edit
        @shop = current_user.shop
    end
    def update
        @shop = Shop.find(params[:id])
        if @shop.update(shop_params)
            flash.notice = 'Shop Edited Successfully!'
        else
            flash.notice = 'Oops! Theres been some issue, Please try later!'
        end
        redirect_to edit_seller_shop_path(@shop.id)
    end

    private
  
    def shop_params
        params.require(:shop).permit(:name, :discount, :value)
    end

end

app/controllers/seller/subscriptions_controller.rb
class Seller::SubscriptionsController < ApplicationController
  
  def new
    @plan = current_user.plan
  end

  def create
    object = CreateSubscription.new
    subscription = object.subscription_create(params[:subscription][:price_id])
  end

  def portalsession
    object = CreateCustomerPortal.new
    portal = object.create_portal_session(current_user.stripe_customer_id)
    redirect_to portal.url
  end

end

app/helpers/subscription_helper.rb
module SubscriptionHelper
end

app/views/seller/subscriptions/new.html.erb
<style>

    .card1:hover {
      background:#00ffb6;
      border:1px solid #00ffb6;
    }

    .card1:hover .list-group-item{
      background:#00ffb6 !important
    }


    


    .card2:hover {
      background:#00C9FF;
      border:1px solid #00C9FF;
    }

    .card2:hover .list-group-item{
      background:#00C9FF !important
    }


    .card3:hover {
      background:#ff95e9;
      border:1px solid #ff95e9;
    }

    .card3:hover .list-group-item{
      background:#ff95e9 !important
    }


    .card:hover .btn-outline-dark{
      color:white;
      background:#212529;
    }

  </style>

  <div class="container-fluid" style="margin-left:160px">
    <div class="container p-5">
      <div class="row">
        <div class="col-lg-4 col-md-12 mb-4">
          <div class="card card1 h-100">
            <div class="card-body">
             
              <h5 class="card-title"><%=@plan.name%></h5>
              <small class='text-muted'>Current Subscription</small>
              <br><br>
              <span class="h2">$<%=@plan.display_price%></span>/month
              <br><br>
                <%= link_to 'Manage Plan', portalsession_seller_subscription_path(current_user.id) , :class => 'list-group-item list-group-item-action py-2 ripple' %>
            </div>

            
          </div>
        </div>
      </div>    
    </div>